Provision postgres secret
bcgov/traction-tenant-traceability-controller pull request #18
Opened 2024-04-26 13:34 UTC by PatStLouis

Source an environment variable in the controller based on the created postgresql secret. Replaced the portion of the postgres uri with this variable. This will need a review.

2024-05-08 21:52 UTC, i5okie requested changes

2024-05-08 22:45 UTC, PatStLouis commented on charts/traction-tenant-traceability-controller/templates/controller/environment.yaml
> -  POSTGRES_URI: postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.secretKeys.userPasswordKey }}@{{ include "global.postgresql.fullname" . }}:{{ .Values.postgresql.primary.s
Correct me if I'm wrong but won't this only provision the password key label as a value and not the password itself?

2024-05-08 22:48 UTC, PatStLouis commented on charts/traction-tenant-traceability-controller/templates/controller/deployment.yaml
> +                configMapKeyRef:
my bad, it should be `secretKeyRef`. The secret will be created by the postgresql bitnami chart. The current process is to deploy the chart, then go fetch the postgresql secret and replace the correct value in the controller secret POSTGRES_URI then redeploy to container to load the new value.

What I'm trying to achieve here is define an environment variable in the controller based on the existing secret created in the postgresql deployment, then refer this variable as part of the POSTGRES_URI variable.

This is based on
[](https://github.com/bcgov/traction/blob/0dba6560d42ca7022b0a9d0d15b7273ffc22d45c/charts/traction/templates/_helpers.tpl#L133)
[](https://github.com/bcgov/traction/blob/0dba6560d42ca7022b0a9d0d15b7273ffc22d45c/charts/traction/templates/acapy/database_secret.yaml#L13)

2024-05-08 22:50 UTC, PatStLouis commented on charts/traction-tenant-traceability-controller/templates/controller/environment.yaml
> -  POSTGRES_URI: postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.secretKeys.userPasswordKey }}@{{ include "global.postgresql.fullname" . }}:{{ .Values.postgresql.primary.s
This is the current value and does not provision the password value
https://github.com/bcgov/traction-tenant-traceability-controller/blob/b5fc794e0ffafb9b9085c2e7663b804e25242ace/charts/traction-tenant-traceability-controller/templates/controller/environment.yaml#L8

2024-05-10 15:15 UTC, esune approved these changes

2024-05-10 15:17 UTC, merged