chore: updating dependabot file to support GHA, Python and docker packages
bcgov/traction-tenant-traceability-controller pull request #22
Opened 2024-05-29 17:56 UTC by rajpalc7

2024-05-29 17:58 UTC, rajpalc7 commented
Hi @WadeBarnes , this is ready for review now

2024-05-30 13:57 UTC, WadeBarnes requested changes
This project contains helm chats too.

2024-05-31 15:27 UTC, rajpalc7 commented
@WadeBarnes - this is ready for review.

2024-05-31 16:13 UTC, WadeBarnes approved these changes

2024-05-31 16:13 UTC, merged